import {
  IconBarbellFilled,
  IconCoins,
  IconDeviceGamepad2,
  IconDeviceTvFilled,
  IconBasketFilled,
  IconHanger,
  IconCashBanknoteFilled,
  IconCarFilled,
  IconHomeFilled,
  IconTimeline,
  IconGlassCocktail,
  IconGiftFilled,
  IconCreditCardFilled,
  IconBurger,
  IconBulbFilled,
} from "@tabler/icons-react";

export const ICONS_MAP = {
  IconBasketFilled: IconBasketFilled,
  IconHomeFilled: IconHomeFilled,
  IconCarFilled: IconCarFilled,
  IconCashBanknoteFilled: IconCashBanknoteFilled,
  IconHanger: IconHanger,
  IconBarbellFilled: IconBarbellFilled,
  IconDeviceGamepad2: IconDeviceGamepad2,
  IconDeviceTvFilled: IconDeviceTvFilled,
  IconCoins: IconCoins,
  IconBulbFilled: IconBulbFilled,
  IconBurger: IconBurger,
  IconCreditCardFilled: IconCreditCardFilled,
  IconGiftFilled: IconGiftFilled,
  IconGlassCocktail: IconGlassCocktail,
  IconTimeline: IconTimeline,
};
